### ISSUE TITLE
{x, y}_column field in metadata

### ISSUE THREAD

**Issue by georgievgeorgi** [h2020charisma/ramanchada2#132]
if a header is present in the input file, the column name for x and y data should be stored in the corresponding `x_column` and `y_column` field in metadata.

**Comment by vedina** [comment]
We may adopt NeXus format notations https://manual.nexusformat.org/classes/base_classes/NXdata.html *

@signal is  y_column   
@axes is array of strings reflecting the x axes  (Spectrum support single axis so far , so that would be [ "RamanShift" ] or ["wavelength"] , etc

@auxiliary_signals: (optional) is also array of strings, and could be a good place for other columns eventualy to be read from the files, including dark background

* (would be easier for Spectrum -> NeXus conversions)

**Comment by georgievgeorgi** [comment]
store information whether y-data are:
- background
- background subtracted
- raw spectrum with background
